# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_from <- function(clust, return_partitions = FALSE) {
    .Call('_CPLogit_dist_from', PACKAGE = 'CPLogit', clust, return_partitions)
}

DPgibbsLinear <- function(X_list0, Y_list0, Z_prior, psi_par, H, H_upper, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_DPgibbsLinear', PACKAGE = 'CPLogit', X_list0, Y_list0, Z_prior, psi_par, H, H_upper, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

gibbs <- function(X_list0, Y_list0, Z_prior, psi_par, H, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_gibbs', PACKAGE = 'CPLogit', X_list0, Y_list0, Z_prior, psi_par, H, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

DPgibbs <- function(X_list0, Y_list0, Z_prior, psi_par, H, H_upper, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_DPgibbs', PACKAGE = 'CPLogit', X_list0, Y_list0, Z_prior, psi_par, H, H_upper, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

gibbsPGLogit <- function(Y0, X0, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_gibbsPGLogit', PACKAGE = 'CPLogit', Y0, X0, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

gibbsLinearModel <- function(Y0, X0, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_gibbsLinearModel', PACKAGE = 'CPLogit', Y0, X0, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

gibbsGLinearModel <- function(X_list0, Y_list0, Z_prior, psi_par, H, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0) {
    .Call('_CPLogit_gibbsGLinearModel', PACKAGE = 'CPLogit', X_list0, Y_list0, Z_prior, psi_par, H, alpha, a_prior, tau_prior, b_prior, Q_prior, n_iter0)
}

rndpp_mvnormal <- function(n, mean, sigma) {
    .Call('_CPLogit_rndpp_mvnormal', PACKAGE = 'CPLogit', n, mean, sigma)
}

vi_distC <- function(cl1, cl2) {
    .Call('_CPLogit_vi_distC', PACKAGE = 'CPLogit', cl1, cl2)
}

